import pygame
from pygame import *
from Scripts.init import *

class Cible(pygame.sprite.Sprite):
    def __init__(self):
        pygame.sprite.Sprite.__init__(self)
        self.images = []
        self.images.append(pygame.image.load('./assets/Images/Boule.png'))
        self.images.append(pygame.image.load('./assets/Images/BouleG.png'))
        self.images.append(pygame.image.load('./assets/Images/BouleGold.png'))
        for i in range(len(self.images)):
            self.images[i] = pygame.transform.scale(self.images[i], (LARGEUR_ECRAN*0.25, HAUTEUR_ECRAN*0.44))
        self.image = self.images[0]
        self.rect = self.image.get_rect()
class ColoredRing(pygame.sprite.Sprite):
    def __init__(self):
       # Call the parent class (Sprite) constructor
        pygame.sprite.Sprite.__init__(self)
        self.images = []
        self.images.append(pygame.image.load('./assets/Images/Background/redring.png'))
        self.images.append(pygame.image.load('./assets/Images/Background/greenring.png'))
        for i in range(len(self.images)):
            self.images[i] = pygame.transform.scale(self.images[i], (258 * LARGEUR_ECRAN/1920, 395 * HAUTEUR_ECRAN/1080))
        self.image = self.images[0]
        self.rect = self.image.get_rect()
class Background(pygame.sprite.Sprite):

    # Constructor. Pass in the color of the block,
    # and its x and y position
    def __init__(self):
       # Call the parent class (Sprite) constructor
        pygame.sprite.Sprite.__init__(self)
        self.images = []
        self.images.append(pygame.image.load('./assets/Images/Background/1.jpg'))
        self.images.append(pygame.image.load('./assets/Images/Background/1.png'))
        self.images.append(pygame.image.load('./assets/Images/Background/2.jpg'))
        for i in range(len(self.images)):
            self.images[i] = pygame.transform.scale(self.images[i], (LARGEUR_ECRAN, HAUTEUR_ECRAN))
        self.image = self.images[0]
        self.rect = self.image.get_rect()
class BackgroudFrame(pygame.sprite.Sprite):
    
    # Constructor. Pass in the color of the block,
    # and its x and y position
    def __init__(self):
       # Call the parent class (Sprite) constructor
        pygame.sprite.Sprite.__init__(self)
     
        self.images = []
        self.images.append(pygame.image.load('./assets/Images/frame/1.png'))
        self.images.append(pygame.image.load('./assets/Images/frame/2.png'))
        self.images.append(pygame.image.load('./assets/Images/frame/3.png'))
        self.images.append(pygame.image.load('./assets/Images/frame/4.png'))
        self.images.append(pygame.image.load('./assets/Images/frame/5.png'))
        self.images.append(pygame.image.load('./assets/Images/frame/6.png'))
        self.images.append(pygame.image.load('./assets/Images/frame/7.png'))
        self.images.append(pygame.image.load('./assets/Images/frame/8.png'))
        self.images.append(pygame.image.load('./assets/Images/frame/9.png'))
        self.images.append(pygame.image.load('./assets/Images/frame/10.png'))
        self.images.append(pygame.image.load('./assets/Images/frame/11.png'))
        self.images.append(pygame.image.load('./assets/Images/frame/12.png'))
        self.images.append(pygame.image.load('./assets/Images/frame/13.png'))
        self.images.append(pygame.image.load('./assets/Images/frame/14.png'))
        self.images.append(pygame.image.load('./assets/Images/frame/15.png'))
        self.images.append(pygame.image.load('./assets/Images/frame/16.png'))
        self.images.append(pygame.image.load('./assets/Images/frame/17.png'))
        self.images.append(pygame.image.load('./assets/Images/frame/18.png'))
        self.images.append(pygame.image.load('./assets/Images/frame/19.png'))
        self.images.append(pygame.image.load('./assets/Images/frame/20.png'))
        self.images.append(pygame.image.load('./assets/Images/frame/21.png'))
        self.images.append(pygame.image.load('./assets/Images/frame/22.png'))
        self.images.append(pygame.image.load('./assets/Images/frame/23.png'))
        self.images.append(pygame.image.load('./assets/Images/frame/24.png'))
        self.index = 0
        for i in range(len(self.images)):
            self.images[i] = pygame.transform.scale(self.images[i], (LARGEUR_ECRAN, HAUTEUR_ECRAN))
 
        #now the image that we will display will be the index from the image array 
        self.image = self.images[self.index]
 
        #creating a rect at position x,y (5,5) of size (150,198) which is the size of sprite 
        self.rect = self.image.get_rect()
        self.increaseindex = True
    def update(self):
        #when the update method is called, we will increment the index
        if self.index >= len(self.images) - 1:
            #descrease
            self.increaseindex = False
        
        if self.index <= 0:
            self.increaseindex = True
        
        if self.increaseindex == True:
            self.index += 1
            
        else:
            self.index -= 1
       
        #print(self.index)
        #finally we will update the image that will be displayed
        self.image = self.images[self.index]
class AnimationFrame1(pygame.sprite.Sprite):
    
    # Constructor. Pass in the color of the block,
    # and its x and y position
    def __init__(self):
       # Call the parent class (Sprite) constructor
        pygame.sprite.Sprite.__init__(self)
        self.images = []
        self.images.append(pygame.image.load('./assets/Images/vid1/1.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/2.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/3.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/4.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/5.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/6.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/7.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/8.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/9.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/10.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/11.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/12.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/13.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/14.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/15.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/16.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/17.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/18.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/19.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/20.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/21.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/22.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/23.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/24.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/25.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/26.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/27.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/28.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/29.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/30.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/31.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/32.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/33.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/34.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/35.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/36.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/37.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/38.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/39.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/40.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/41.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/42.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/43.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/44.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/45.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/46.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/47.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/48.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/49.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/50.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/51.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/52.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/53.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/54.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/55.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/56.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/57.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/58.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/59.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/60.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/61.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/62.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/63.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/64.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/65.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/66.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/67.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/68.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/69.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/70.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/71.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/72.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/73.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/74.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/75.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/76.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/77.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/78.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/79.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/80.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/81.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/82.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/83.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/84.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/85.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/86.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/87.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/88.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/89.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/90.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/91.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/92.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/93.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/94.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/95.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/96.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/97.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/98.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/99.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/100.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/101.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/102.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/103.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/104.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/105.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/106.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/107.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/108.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/109.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/110.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/111.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/112.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/113.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/114.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/115.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/116.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/117.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/118.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/119.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/120.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/121.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/122.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/123.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/124.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/125.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/126.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/127.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/128.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/129.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/130.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/131.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/132.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/133.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/134.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/135.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/136.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/137.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/138.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/139.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/140.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/141.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/142.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/143.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/144.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/145.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/146.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/147.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/148.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/149.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/150.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/151.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/152.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/153.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/154.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/155.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/156.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/157.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/158.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/159.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/160.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/161.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/162.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/163.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/164.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/165.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/166.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/167.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/168.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/169.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/170.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/171.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/172.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/173.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/174.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/175.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/176.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/177.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/178.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/179.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/180.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/181.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/182.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/183.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/184.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/185.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/186.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/187.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/188.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/189.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/190.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/191.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/192.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/193.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/194.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/195.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/196.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/197.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/198.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/199.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/200.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/201.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/202.png'))
        self.images.append(pygame.image.load('./assets/Images/vid1/203.png'))
        self.index = 0
        self.img_width, self.img_height = self.images[1].get_rect().size
        self.res_img_width=self.img_width*LARGEUR_ECRAN/1920/2
        self.res_img_height=self.img_height*HAUTEUR_ECRAN/1080/2
        for i in range(len(self.images)):
            self.images[i] = pygame.transform.scale(self.images[i], (self.img_width*LARGEUR_ECRAN/1920/2,self.img_height*HAUTEUR_ECRAN/1080/2))
 
        #now the image that we will display will be the index from the image array 
        self.image = self.images[self.index]
 
        #creating a rect at position x,y (5,5) of size (150,198) which is the size of sprite 
        self.rect = self.image.get_rect()
        self.increaseindex = True
    def update(self):
        #when the update method is called, we will increment the index
        if self.index >= len(self.images) - 1:
            #descrease
            self.index=0
            #self.increaseindex = False
        self.index += 1
        
        #print(self.index)
        #finally we will update the image that will be displayed
        self.image = self.images[self.index]
class AnimationFrame2(pygame.sprite.Sprite):
    
    # Constructor. Pass in the color of the block,
    # and its x and y position
    def __init__(self):
       # Call the parent class (Sprite) constructor
        pygame.sprite.Sprite.__init__(self)
     
        self.images = []
        self.images.append(pygame.image.load('./assets/Images/vid2/1.png'))
        self.images.append(pygame.image.load('./assets/Images/vid2/2.png'))
        self.images.append(pygame.image.load('./assets/Images/vid2/3.png'))
        self.images.append(pygame.image.load('./assets/Images/vid2/4.png'))
        self.images.append(pygame.image.load('./assets/Images/vid2/5.png'))
        self.images.append(pygame.image.load('./assets/Images/vid2/6.png'))
        self.images.append(pygame.image.load('./assets/Images/vid2/7.png'))
        self.images.append(pygame.image.load('./assets/Images/vid2/8.png'))
        self.images.append(pygame.image.load('./assets/Images/vid2/9.png'))
        self.images.append(pygame.image.load('./assets/Images/vid2/10.png'))
        self.images.append(pygame.image.load('./assets/Images/vid2/11.png'))
        self.images.append(pygame.image.load('./assets/Images/vid2/12.png'))
        self.images.append(pygame.image.load('./assets/Images/vid2/13.png'))
        self.images.append(pygame.image.load('./assets/Images/vid2/14.png'))
        self.images.append(pygame.image.load('./assets/Images/vid2/15.png'))
        self.images.append(pygame.image.load('./assets/Images/vid2/16.png'))
        self.images.append(pygame.image.load('./assets/Images/vid2/17.png'))
        self.images.append(pygame.image.load('./assets/Images/vid2/18.png'))
        self.images.append(pygame.image.load('./assets/Images/vid2/19.png'))
        self.images.append(pygame.image.load('./assets/Images/vid2/20.png'))
        self.images.append(pygame.image.load('./assets/Images/vid2/21.png'))
        self.index = 0
        self.img_width, self.img_height = self.images[1].get_rect().size
        self.res_img_width=self.img_width*LARGEUR_ECRAN/1920/2
        self.res_img_height=self.img_height*HAUTEUR_ECRAN/1080/2
        for i in range(len(self.images)):
            self.images[i] = pygame.transform.scale(self.images[i], (self.img_width*LARGEUR_ECRAN/1920/2,self.img_height*HAUTEUR_ECRAN/1080/2))
 
        #now the image that we will display will be the index from the image array 
        self.image = self.images[self.index]

        #creating a rect at position x,y (5,5) of size (150,198) which is the size of sprite 
        self.rect = self.image.get_rect()
        self.increaseindex = True
    def update(self):
        #when the update method is called, we will increment the index
        if self.index >= len(self.images) - 1:
            #descrease
            self.index=0
            #self.increaseindex = False
        self.index += 1
        
        #print(self.index)
        #finally we will update the image that will be displayed
        self.image = self.images[self.index]
class AnimationFrame3(pygame.sprite.Sprite):
    
    # Constructor. Pass in the color of the block,
    # and its x and y position
    def __init__(self):
       # Call the parent class (Sprite) constructor
        pygame.sprite.Sprite.__init__(self)
     
        self.images = []
        self.images.append(pygame.image.load('./assets/Images/vid3/1.png'))
        self.images.append(pygame.image.load('./assets/Images/vid3/2.png'))
        self.images.append(pygame.image.load('./assets/Images/vid3/3.png'))
        self.images.append(pygame.image.load('./assets/Images/vid3/4.png'))
        self.images.append(pygame.image.load('./assets/Images/vid3/5.png'))
        self.images.append(pygame.image.load('./assets/Images/vid3/6.png'))
        self.images.append(pygame.image.load('./assets/Images/vid3/7.png'))
        self.images.append(pygame.image.load('./assets/Images/vid3/8.png'))
        self.images.append(pygame.image.load('./assets/Images/vid3/9.png'))
        self.images.append(pygame.image.load('./assets/Images/vid3/10.png'))
        self.images.append(pygame.image.load('./assets/Images/vid3/11.png'))
        self.images.append(pygame.image.load('./assets/Images/vid3/12.png'))
        self.images.append(pygame.image.load('./assets/Images/vid3/13.png'))
        self.images.append(pygame.image.load('./assets/Images/vid3/14.png'))
        self.images.append(pygame.image.load('./assets/Images/vid3/15.png'))
        self.images.append(pygame.image.load('./assets/Images/vid3/16.png'))
        self.images.append(pygame.image.load('./assets/Images/vid3/17.png'))
        self.images.append(pygame.image.load('./assets/Images/vid3/18.png'))
        self.images.append(pygame.image.load('./assets/Images/vid3/19.png'))
        self.images.append(pygame.image.load('./assets/Images/vid3/20.png'))
        self.images.append(pygame.image.load('./assets/Images/vid3/21.png'))
        self.images.append(pygame.image.load('./assets/Images/vid3/22.png'))
        self.images.append(pygame.image.load('./assets/Images/vid3/23.png'))
        self.images.append(pygame.image.load('./assets/Images/vid3/24.png'))
        self.images.append(pygame.image.load('./assets/Images/vid3/25.png'))
        self.images.append(pygame.image.load('./assets/Images/vid3/26.png'))
        self.images.append(pygame.image.load('./assets/Images/vid3/27.png'))
        self.images.append(pygame.image.load('./assets/Images/vid3/28.png'))
        self.images.append(pygame.image.load('./assets/Images/vid3/29.png'))
        self.images.append(pygame.image.load('./assets/Images/vid3/30.png'))
        self.images.append(pygame.image.load('./assets/Images/vid3/31.png'))
        self.images.append(pygame.image.load('./assets/Images/vid3/32.png'))
        self.images.append(pygame.image.load('./assets/Images/vid3/33.png'))
        self.images.append(pygame.image.load('./assets/Images/vid3/34.png'))
        self.images.append(pygame.image.load('./assets/Images/vid3/35.png'))
        self.images.append(pygame.image.load('./assets/Images/vid3/36.png'))
        self.images.append(pygame.image.load('./assets/Images/vid3/37.png'))
        self.images.append(pygame.image.load('./assets/Images/vid3/38.png'))
        self.index = 0
        self.img_width, self.img_height = self.images[1].get_rect().size
        self.res_img_width=self.img_width*LARGEUR_ECRAN/1920/2
        self.res_img_height=self.img_height*HAUTEUR_ECRAN/1080/2
        for i in range(len(self.images)):
            self.images[i] = pygame.transform.scale(self.images[i], (self.img_width*LARGEUR_ECRAN/1920/2,self.img_height*HAUTEUR_ECRAN/1080/2))
 
        #now the image that we will display will be the index from the image array 
        self.image = self.images[self.index]

 
        #creating a rect at position x,y (5,5) of size (150,198) which is the size of sprite 
        self.rect = self.image.get_rect()
        self.increaseindex = True
    def update(self):
        #when the update method is called, we will increment the index
        if self.index >= len(self.images) - 1:
            #descrease
            self.index=0
            #self.increaseindex = False
        self.index += 1
        
        #print(self.index)
        #finally we will update the image that will be displayed
        self.image = self.images[self.index]
class AnimationFrame4(pygame.sprite.Sprite):
    
    # Constructor. Pass in the color of the block,
    # and its x and y position
    def __init__(self):
       # Call the parent class (Sprite) constructor
        pygame.sprite.Sprite.__init__(self)
     
        self.images = []
        self.images.append(pygame.image.load('./assets/Images/vid4/1.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/2.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/3.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/4.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/5.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/6.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/7.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/8.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/9.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/10.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/11.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/12.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/13.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/14.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/15.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/16.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/17.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/18.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/19.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/20.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/21.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/22.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/23.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/24.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/25.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/26.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/27.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/28.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/29.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/30.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/31.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/32.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/33.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/34.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/35.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/36.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/37.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/38.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/39.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/40.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/41.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/42.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/43.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/44.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/45.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/46.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/47.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/48.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/49.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/50.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/51.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/52.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/53.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/54.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/55.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/56.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/57.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/58.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/59.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/60.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/61.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/62.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/63.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/64.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/65.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/66.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/67.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/68.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/69.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/70.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/71.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/72.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/73.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/74.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/75.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/76.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/77.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/78.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/79.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/80.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/81.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/82.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/83.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/84.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/85.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/86.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/87.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/88.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/89.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/90.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/91.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/92.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/93.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/94.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/95.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/96.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/97.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/98.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/99.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/100.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/101.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/102.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/103.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/104.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/105.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/106.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/107.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/108.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/109.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/110.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/111.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/112.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/113.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/114.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/115.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/116.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/117.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/118.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/119.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/120.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/121.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/122.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/123.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/124.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/125.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/126.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/127.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/128.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/129.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/130.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/131.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/132.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/133.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/134.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/135.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/136.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/137.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/138.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/139.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/140.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/141.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/142.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/143.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/144.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/145.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/146.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/147.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/148.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/149.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/150.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/151.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/152.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/153.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/154.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/155.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/156.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/157.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/158.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/159.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/160.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/161.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/162.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/163.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/164.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/165.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/166.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/167.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/168.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/169.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/170.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/171.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/172.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/173.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/174.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/175.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/176.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/177.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/178.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/179.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/180.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/181.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/182.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/183.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/184.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/185.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/186.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/187.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/188.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/189.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/190.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/191.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/192.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/193.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/194.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/195.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/196.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/197.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/198.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/199.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/200.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/201.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/202.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/203.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/204.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/205.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/206.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/207.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/208.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/209.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/210.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/211.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/212.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/213.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/214.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/215.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/216.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/217.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/218.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/219.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/220.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/221.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/222.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/223.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/224.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/225.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/226.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/227.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/228.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/229.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/230.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/231.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/232.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/233.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/234.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/235.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/236.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/237.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/238.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/239.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/240.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/241.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/242.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/243.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/244.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/245.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/246.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/247.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/248.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/249.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/250.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/251.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/252.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/253.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/254.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/255.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/256.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/257.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/258.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/259.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/260.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/261.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/262.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/263.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/264.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/265.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/266.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/267.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/268.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/269.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/270.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/271.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/272.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/273.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/274.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/275.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/276.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/277.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/278.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/279.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/280.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/281.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/282.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/283.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/284.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/285.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/286.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/287.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/288.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/289.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/290.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/291.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/292.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/293.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/294.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/295.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/296.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/297.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/298.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/299.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/300.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/301.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/302.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/303.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/304.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/305.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/306.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/307.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/308.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/309.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/310.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/311.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/312.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/313.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/314.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/315.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/316.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/317.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/318.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/319.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/320.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/321.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/322.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/323.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/324.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/325.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/326.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/327.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/328.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/329.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/330.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/331.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/332.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/333.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/334.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/335.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/336.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/337.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/338.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/339.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/340.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/341.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/342.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/343.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/344.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/345.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/346.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/347.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/348.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/349.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/350.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/351.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/352.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/353.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/354.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/355.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/356.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/357.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/358.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/359.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/360.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/361.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/362.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/363.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/364.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/365.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/366.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/367.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/368.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/369.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/370.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/371.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/372.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/373.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/374.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/375.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/376.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/377.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/378.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/379.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/380.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/381.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/382.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/383.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/384.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/385.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/386.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/387.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/388.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/389.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/390.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/391.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/392.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/393.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/394.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/395.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/396.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/397.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/398.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/399.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/400.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/401.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/402.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/403.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/404.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/405.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/406.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/407.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/408.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/409.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/410.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/411.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/412.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/413.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/414.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/415.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/416.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/417.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/418.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/419.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/420.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/421.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/422.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/423.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/424.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/425.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/426.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/427.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/428.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/429.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/430.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/431.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/432.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/433.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/434.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/435.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/436.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/437.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/438.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/439.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/440.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/441.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/442.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/443.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/444.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/445.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/446.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/447.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/448.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/449.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/450.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/451.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/452.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/453.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/454.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/455.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/456.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/457.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/458.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/459.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/460.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/461.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/462.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/463.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/464.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/465.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/466.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/467.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/468.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/469.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/470.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/471.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/472.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/473.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/474.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/475.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/476.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/477.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/478.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/479.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/480.png'))
        self.images.append(pygame.image.load('./assets/Images/vid4/481.png'))
        self.index = 0
        self.img_width, self.img_height = self.images[1].get_rect().size
        self.res_img_width=self.img_width*LARGEUR_ECRAN/1920/2
        self.res_img_height=self.img_height*HAUTEUR_ECRAN/1080/2
        for i in range(len(self.images)):
            self.images[i] = pygame.transform.scale(self.images[i], (self.img_width*LARGEUR_ECRAN/1920/2,self.img_height*HAUTEUR_ECRAN/1080/2))
 
        #now the image that we will display will be the index from the image array 
        self.image = self.images[self.index]

 
        #creating a rect at position x,y (5,5) of size (150,198) which is the size of sprite 
        self.rect = self.image.get_rect()
        self.increaseindex = True
    def update(self):
        #when the update method is called, we will increment the index
        if self.index >= len(self.images) - 1:
            #descrease
            self.index=0
            #self.increaseindex = False
        self.index += 1
        
        #print(self.index)
        #finally we will update the image that will be displayed
        self.image = self.images[self.index]
        #clock.tick(15) #

